//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.27 at 03:33:41 PM BRT 
//


package com.in28minutes.students;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.in28minutes.students package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.in28minutes.students
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetStudentDetailsResponse }
     * 
     */
    public GetStudentDetailsResponse createGetStudentDetailsResponse() {
        return new GetStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link StudentDetails }
     * 
     */
    public StudentDetails createStudentDetails() {
        return new StudentDetails();
    }

    /**
     * Create an instance of {@link AddStudentDetailsRequest }
     * 
     */
    public AddStudentDetailsRequest createAddStudentDetailsRequest() {
        return new AddStudentDetailsRequest();
    }

    /**
     * Create an instance of {@link DeleteStudentDetailsRequest }
     * 
     */
    public DeleteStudentDetailsRequest createDeleteStudentDetailsRequest() {
        return new DeleteStudentDetailsRequest();
    }

    /**
     * Create an instance of {@link AddStudentDetailsResponse }
     * 
     */
    public AddStudentDetailsResponse createAddStudentDetailsResponse() {
        return new AddStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link DeleteStudentDetailsResponse }
     * 
     */
    public DeleteStudentDetailsResponse createDeleteStudentDetailsResponse() {
        return new DeleteStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link UpdateStudentDetailsRequest }
     * 
     */
    public UpdateStudentDetailsRequest createUpdateStudentDetailsRequest() {
        return new UpdateStudentDetailsRequest();
    }

    /**
     * Create an instance of {@link UpdateStudentDetailsResponse }
     * 
     */
    public UpdateStudentDetailsResponse createUpdateStudentDetailsResponse() {
        return new UpdateStudentDetailsResponse();
    }

    /**
     * Create an instance of {@link GetStudentDetailsRequest }
     * 
     */
    public GetStudentDetailsRequest createGetStudentDetailsRequest() {
        return new GetStudentDetailsRequest();
    }

}
